# Generated by Django 4.0.4 on 2023-02-17 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stock',
            name='current_prices',
        ),
    ]
