# Generated by Django 4.0.4 on 2023-02-19 07:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('brands', '0002_brand_sort_order_brandcategory_code'),
        ('stock', '0002_remove_stock_current_prices'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='brand',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stocks', to='brands.brand'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='date',
            field=models.DateField(),
        ),
    ]
