# Generated by Django 4.0.4 on 2023-01-28 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brands', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='sort_order',
            field=models.IntegerField(default=None, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='brandcategory',
            name='code',
            field=models.CharField(default='1', max_length=50, unique=True),
            preserve_default=False,
        ),
    ]
