# Generated by Django 4.0.4 on 2023-02-17 13:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('brands', '0002_brand_sort_order_brandcategory_code'),
        ('prices', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='price',
            name='brand',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='brands.brand'),
        ),
    ]
