# Generated by Django 4.0.4 on 2023-01-25 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Balance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_date', models.DateField(unique=True)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
                ('bank', models.FloatField()),
                ('handcash', models.FloatField()),
                ('loose', models.FloatField()),
                ('credits', models.FloatField()),
                ('remarks', models.CharField(max_length=200)),
            ],
        ),
    ]
