# Generated by Django 4.0.4 on 2023-01-25 17:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('brands', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReceitMeta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(max_length=150, unique=True)),
                ('dd_amount', models.FloatField()),
                ('invoice_amount', models.FloatField()),
                ('given_by', models.CharField(max_length=100)),
                ('took_by', models.CharField(max_length=100)),
                ('extra_data', models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='Receit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('date', models.DateField(auto_now_add=True)),
                ('updated_date', models.DateField(auto_now=True)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='brands.brand')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='receits.receitmeta')),
            ],
        ),
    ]
