# Generated by Django 4.0.4 on 2023-02-25 07:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('brands', '0002_brand_sort_order_brandcategory_code'),
        ('receits', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receit',
            name='brand',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receits', to='brands.brand'),
        ),
        migrations.AlterField(
            model_name='receit',
            name='date',
            field=models.DateField(),
        ),
    ]
