# Generated by Django 4.0.4 on 2023-01-25 17:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cash', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dailysale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('created', models.DateField(auto_now_add=True)),
                ('updated_date', models.DateField(auto_now=True)),
                ('total', models.FloatField()),
                ('details', models.JSONField()),
                ('person', models.CharField(max_length=100)),
                ('remarks', models.CharField(max_length=200)),
                ('cash_details', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cash.balance')),
            ],
        ),
    ]
